"""Initial domain schema."""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizers",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','approved','suspended')", name=op.f("ck_organizers_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizers")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizers_slug")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_admin", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("email = lower(trim(email))", name=op.f("ck_users_normalized_email")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "events",
        sa.Column("organizer_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("format", sa.String(length=20), server_default="in_person", nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="Asia/Kolkata", nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("venue", sa.String(length=300), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("online_url", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("format IN ('in_person','online')", name=op.f("ck_events_format")),
        sa.CheckConstraint(
            "status IN ('draft','published','cancelled')", name=op.f("ck_events_status")
        ),
        sa.CheckConstraint(
            "ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at",
            name=op.f("ck_events_timing"),
        ),
        sa.ForeignKeyConstraint(
            ["organizer_id"], ["organizers.id"], name=op.f("fk_events_organizer_id_organizers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("id", "organizer_id", name=op.f("uq_events_id")),
        sa.UniqueConstraint("slug", name=op.f("uq_events_slug")),
    )
    op.create_index(op.f("ix_events_city"), "events", ["city"], unique=False)
    op.create_index(op.f("ix_events_organizer_id"), "events", ["organizer_id"], unique=False)
    op.create_index(op.f("ix_events_starts_at"), "events", ["starts_at"], unique=False)
    op.create_index(op.f("ix_events_status"), "events", ["status"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("organizer_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner','editor','check_in')", name=op.f("ck_memberships_role")
        ),
        sa.ForeignKeyConstraint(
            ["organizer_id"], ["organizers.id"], name=op.f("fk_memberships_organizer_id_organizers")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint("organizer_id", "user_id", name=op.f("uq_memberships_organizer_id")),
    )
    op.create_index(
        op.f("ix_memberships_organizer_id"), "memberships", ["organizer_id"], unique=False
    )
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "bookings",
        sa.Column("organizer_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("total_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'INR'", name=op.f("ck_bookings_currency")),
        sa.CheckConstraint(
            "status IN ('pending','confirmed','expired','cancelled')",
            name=op.f("ck_bookings_status"),
        ),
        sa.CheckConstraint("total_minor >= 0", name=op.f("ck_bookings_total")),
        sa.ForeignKeyConstraint(
            ["event_id", "organizer_id"],
            ["events.id", "events.organizer_id"],
            name=op.f("fk_bookings_event_id_events"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_bookings_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
        sa.UniqueConstraint("id", "event_id", "organizer_id", name=op.f("uq_bookings_id")),
        sa.UniqueConstraint("user_id", "idempotency_key", name=op.f("uq_bookings_user_id")),
    )
    op.create_index(op.f("ix_bookings_event_id"), "bookings", ["event_id"], unique=False)
    op.create_index(op.f("ix_bookings_expires_at"), "bookings", ["expires_at"], unique=False)
    op.create_index(op.f("ix_bookings_organizer_id"), "bookings", ["organizer_id"], unique=False)
    op.create_index(op.f("ix_bookings_user_id"), "bookings", ["user_id"], unique=False)
    op.create_table(
        "ticket_types",
        sa.Column("organizer_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("price_minor", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'INR'", name=op.f("ck_ticket_types_currency")),
        sa.CheckConstraint("capacity >= 0", name=op.f("ck_ticket_types_capacity")),
        sa.CheckConstraint("price_minor >= 0", name=op.f("ck_ticket_types_price")),
        sa.ForeignKeyConstraint(
            ["event_id", "organizer_id"],
            ["events.id", "events.organizer_id"],
            name=op.f("fk_ticket_types_event_id_events"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_types")),
        sa.UniqueConstraint("id", "event_id", "organizer_id", name=op.f("uq_ticket_types_id")),
    )
    op.create_index(op.f("ix_ticket_types_event_id"), "ticket_types", ["event_id"], unique=False)
    op.create_index(
        op.f("ix_ticket_types_organizer_id"), "ticket_types", ["organizer_id"], unique=False
    )
    op.create_table(
        "tickets",
        sa.Column("organizer_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_type_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("price_minor", sa.BigInteger(), nullable=False),
        sa.Column("qr_token_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="valid", nullable=False),
        sa.Column("admitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("admitted_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('valid','cancelled')", name=op.f("ck_tickets_status")),
        sa.CheckConstraint("price_minor >= 0", name=op.f("ck_tickets_price")),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_tickets_sequence")),
        sa.ForeignKeyConstraint(
            ["admitted_by"], ["users.id"], name=op.f("fk_tickets_admitted_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["booking_id", "event_id", "organizer_id"],
            ["bookings.id", "bookings.event_id", "bookings.organizer_id"],
            name=op.f("fk_tickets_booking_id_bookings"),
        ),
        sa.ForeignKeyConstraint(
            ["ticket_type_id", "event_id", "organizer_id"],
            ["ticket_types.id", "ticket_types.event_id", "ticket_types.organizer_id"],
            name=op.f("fk_tickets_ticket_type_id_ticket_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
        sa.UniqueConstraint("booking_id", "sequence", name=op.f("uq_tickets_booking_id")),
        sa.UniqueConstraint("qr_token_hash", name=op.f("uq_tickets_qr_token_hash")),
    )
    op.create_index(op.f("ix_tickets_booking_id"), "tickets", ["booking_id"], unique=False)
    op.create_index(op.f("ix_tickets_event_id"), "tickets", ["event_id"], unique=False)
    op.create_index(op.f("ix_tickets_organizer_id"), "tickets", ["organizer_id"], unique=False)
    op.create_index(op.f("ix_tickets_ticket_type_id"), "tickets", ["ticket_type_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tickets_ticket_type_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_organizer_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_event_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_booking_id"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_ticket_types_organizer_id"), table_name="ticket_types")
    op.drop_index(op.f("ix_ticket_types_event_id"), table_name="ticket_types")
    op.drop_table("ticket_types")
    op.drop_index(op.f("ix_bookings_user_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_organizer_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_expires_at"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_event_id"), table_name="bookings")
    op.drop_table("bookings")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_organizer_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_events_status"), table_name="events")
    op.drop_index(op.f("ix_events_starts_at"), table_name="events")
    op.drop_index(op.f("ix_events_organizer_id"), table_name="events")
    op.drop_index(op.f("ix_events_city"), table_name="events")
    op.drop_table("events")
    op.drop_table("users")
    op.drop_table("organizers")
    # ### end Alembic commands ###
