"""Complete day eight account event ticket and media foundation"""

import sqlalchemy as sa
from alembic import op

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_outbox",
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_outbox")),
    )
    op.create_index(
        op.f("ix_notification_outbox_available_at"),
        "notification_outbox",
        ["available_at"],
        unique=False,
    )
    op.create_table(
        "account_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=20), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "purpose IN ('verify','recover')", name=op.f("ck_account_tokens_purpose")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_account_tokens_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_account_tokens_token_hash")),
    )
    op.create_index(op.f("ix_account_tokens_user_id"), "account_tokens", ["user_id"], unique=False)
    op.create_table(
        "event_media",
        sa.Column("organizer_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="processing", nullable=False),
        sa.Column("source_key", sa.String(length=300), nullable=False),
        sa.Column("image_key", sa.String(length=300), nullable=True),
        sa.Column("thumbnail_key", sa.String(length=300), nullable=True),
        sa.Column("alt_text", sa.String(length=300), nullable=False),
        sa.Column("error", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('poster','gallery')", name=op.f("ck_event_media_kind")),
        sa.CheckConstraint(
            "status IN ('processing','ready','failed')", name=op.f("ck_event_media_status")
        ),
        sa.ForeignKeyConstraint(
            ["event_id", "organizer_id"],
            ["events.id", "events.organizer_id"],
            name=op.f("fk_event_media_event_id_events"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_media")),
        sa.UniqueConstraint("source_key", name=op.f("uq_event_media_source_key")),
    )
    op.create_index(op.f("ix_event_media_event_id"), "event_media", ["event_id"], unique=False)
    op.create_index(
        op.f("ix_event_media_organizer_id"), "event_media", ["organizer_id"], unique=False
    )
    op.create_table(
        "booking_items",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("organizer_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_type_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_minor", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0 AND unit_price_minor >= 0", name=op.f("ck_booking_items_amounts")
        ),
        sa.ForeignKeyConstraint(
            ["booking_id", "event_id", "organizer_id"],
            ["bookings.id", "bookings.event_id", "bookings.organizer_id"],
            name=op.f("fk_booking_items_booking_id_bookings"),
        ),
        sa.ForeignKeyConstraint(
            ["ticket_type_id", "event_id", "organizer_id"],
            ["ticket_types.id", "ticket_types.event_id", "ticket_types.organizer_id"],
            name=op.f("fk_booking_items_ticket_type_id_ticket_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_items")),
        sa.UniqueConstraint(
            "booking_id", "ticket_type_id", name=op.f("uq_booking_items_booking_id")
        ),
    )
    op.create_index(
        op.f("ix_booking_items_booking_id"), "booking_items", ["booking_id"], unique=False
    )
    op.create_table(
        "payment_attempts",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("organizer_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("provider_reference", sa.String(length=200), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_minor >= 0 AND currency = 'INR'", name=op.f("ck_payment_attempts_amount")
        ),
        sa.CheckConstraint(
            "status IN ('pending','paid','failed','refunded')",
            name=op.f("ck_payment_attempts_status"),
        ),
        sa.ForeignKeyConstraint(
            ["booking_id", "event_id", "organizer_id"],
            ["bookings.id", "bookings.event_id", "bookings.organizer_id"],
            name=op.f("fk_payment_attempts_booking_id_bookings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_attempts")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_payment_attempts_idempotency_key")),
        sa.UniqueConstraint(
            "provider_reference", name=op.f("uq_payment_attempts_provider_reference")
        ),
    )
    op.create_index(
        op.f("ix_payment_attempts_booking_id"), "payment_attempts", ["booking_id"], unique=False
    )
    op.add_column("events", sa.Column("category", sa.String(length=80), nullable=True))
    op.add_column("events", sa.Column("cancellation_reason", sa.String(length=1000), nullable=True))
    op.add_column("events", sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_events_category"), "events", ["category"], unique=False)
    op.add_column(
        "ticket_types", sa.Column("sales_start", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("ticket_types", sa.Column("sales_end", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "ticket_types",
        sa.Column("per_order_limit", sa.Integer(), server_default="10", nullable=False),
    )
    with op.batch_alter_table("tickets") as batch:
        batch.create_unique_constraint("uq_tickets_id", ["id", "event_id", "organizer_id"])
    with op.batch_alter_table("ticket_types") as batch:
        batch.create_check_constraint("order_limit", "per_order_limit > 0")
        batch.create_check_constraint(
            "sales_window", "sales_start IS NULL OR sales_end IS NULL OR sales_end > sales_start"
        )
    op.create_table(
        "check_ins",
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("organizer_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_check_ins_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id", "event_id", "organizer_id"],
            ["tickets.id", "tickets.event_id", "tickets.organizer_id"],
            name=op.f("fk_check_ins_ticket_id_tickets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_check_ins")),
        sa.UniqueConstraint("ticket_id", name=op.f("uq_check_ins_ticket_id")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("check_ins")
    with op.batch_alter_table("tickets") as batch:
        batch.drop_constraint("uq_tickets_id", type_="unique")
    with op.batch_alter_table("ticket_types") as batch:
        batch.drop_constraint(op.f("ck_ticket_types_order_limit"), type_="check")
        batch.drop_constraint(op.f("ck_ticket_types_sales_window"), type_="check")
    op.drop_column("ticket_types", "per_order_limit")
    op.drop_column("ticket_types", "sales_end")
    op.drop_column("ticket_types", "sales_start")
    op.drop_index(op.f("ix_events_category"), table_name="events")
    op.drop_column("events", "cancelled_at")
    op.drop_column("events", "cancellation_reason")
    op.drop_column("events", "category")
    op.drop_index(op.f("ix_payment_attempts_booking_id"), table_name="payment_attempts")
    op.drop_table("payment_attempts")
    op.drop_index(op.f("ix_booking_items_booking_id"), table_name="booking_items")
    op.drop_table("booking_items")
    op.drop_index(op.f("ix_event_media_organizer_id"), table_name="event_media")
    op.drop_index(op.f("ix_event_media_event_id"), table_name="event_media")
    op.drop_table("event_media")
    op.drop_index(op.f("ix_account_tokens_user_id"), table_name="account_tokens")
    op.drop_table("account_tokens")
    op.drop_index(op.f("ix_notification_outbox_available_at"), table_name="notification_outbox")
    op.drop_table("notification_outbox")
    # ### end Alembic commands ###
